name: animated_pill
description: A Flutter widget that creates an animated pill-shaped container with customizable appearance and animation properties.
version: 1.0.1
homepage: https://github.com/dubeyanant/animated_pill
repository: https://github.com/dubeyanant/animated_pill.git

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
